
const galleryItems = [
     //equal sizes
     {image : 'assets/gallery/g1.jpg'},
     {image : 'assets/gallery/g2.jpg'},
    //  {image : 'assets/gallery/g3.jpg'},
    //  {image : 'assets/gallery/g4.jpg'},
     {image : 'assets/gallery/g5.jpg'},
     {image : 'assets/gallery/g6.jpg'},
    //  {image : 'assets/gallery/g7.jpg'},
     {image : 'assets/gallery/g8.jpg'},
     {image : 'assets/gallery/g9.jpg'},
     {image : 'assets/gallery/g10.jpg'},
     {image : 'assets/gallery/g11.jpg'},
     {image : 'assets/gallery/g12.jpg'},
     {image : 'assets/gallery/g13.jpg'},
     {image : 'assets/gallery/g14.jpg'},
     {image : 'assets/gallery/g15.jpg'},
     {image : 'assets/gallery/g16.jpg'},
     {image : 'assets/gallery/g17.jpg'},
     {image : 'assets/gallery/g18.jpg'},
     {image : 'assets/gallery/g19.jpg'},
     {image : 'assets/gallery/g20.jpg'},
     {image : 'assets/gallery/g21.jpg'},
     {image : 'assets/gallery/g22.jpg'},
     {image : 'assets/gallery/g23.jpg'},
     {image : 'assets/gallery/g24.jpg'},
     {image : 'assets/gallery/g25.jpg'},
    //  {image : 'assets/gallery/g26.jpg'},
     {image : 'assets/gallery/g27.jpg'},
     {image : 'assets/gallery/g28.jpg'},
     {image : 'assets/gallery/g29.jpg'},
     {image : 'assets/gallery/g30.jpg'},
     {image : 'assets/gallery/g31.jpg'},
     {image : 'assets/gallery/g32.jpg'},
     {image : 'assets/gallery/g33.jpg'},
     {image : 'assets/gallery/g34.jpg'},
     {image : 'assets/gallery/g35.jpg'},
     {image : 'assets/gallery/g36.jpg'},
     {image : 'assets/gallery/g37.jpg'},
     {image : 'assets/gallery/g38.jpg'},
     {image : 'assets/gallery/g39.jpg'},
     {image : 'assets/gallery/g40.jpg'},
     {image : 'assets/gallery/g41.jpg'},
    //  {image : 'assets/gallery/g42.jpg'},
     {image : 'assets/gallery/g43.jpg'},
     {image : 'assets/gallery/g44.jpg'},
     {image : 'assets/gallery/g45.jpg'},
     {image : 'assets/gallery/g46.jpg'},
     {image : 'assets/gallery/g47.jpg'},
     {image : 'assets/gallery/g48.jpg'},
     {image : 'assets/gallery/g49.jpg'},
     {image : 'assets/gallery/g50.jpg'},
     {image : 'assets/gallery/g51.jpg'},
     {image : 'assets/gallery/g52.jpg'},
     {image : 'assets/gallery/g53.jpg'},
     {image : 'assets/gallery/g54.jpg'},
     {image : 'assets/gallery/g55.jpg'},
     {image : 'assets/gallery/g56.jpg'},
     {image : 'assets/gallery/g57.jpg'},
     {image : 'assets/gallery/g58.jpg'},
     {image : 'assets/gallery/g59.jpg'},
     {image : 'assets/gallery/g60.jpg'},
     {image : 'assets/gallery/g61.jpg'},
     {image : 'assets/gallery/g62.jpg'},
     {image : 'assets/gallery/g63.jpg'},
     {image : 'assets/gallery/g64.jpg'},
     {image : 'assets/gallery/g65.jpg'},
     {image : 'assets/gallery/g66.jpg'},
    //  {image : 'assets/gallery/g67.jpg'},
    //  {image : 'assets/gallery/g68.jpg'},
    //  {image : 'assets/gallery/g69.jpg'},
     {image : 'assets/gallery/g70.jpg'},
     {image : 'assets/gallery/g71.jpg'},
    //  {image : 'assets/gallery/g72.jpg'},
     {image : 'assets/gallery/g73.jpg'},
     {image : 'assets/gallery/g74.jpg'},
     {image : 'assets/gallery/g75.jpg'},
     {image : 'assets/gallery/g76.jpg'},
     {image : 'assets/gallery/g77.jpg'},
     {image : 'assets/gallery/g78.jpg'},
     {image : 'assets/gallery/g79.jpg'},
     {image : 'assets/gallery/g80.jpg'},
     {image : 'assets/gallery/g81.jpg'},
     {image : 'assets/gallery/g82.jpg'},
     {image : 'assets/gallery/g83.jpg'},
     {image : 'assets/gallery/g84.jpg'},
     {image : 'assets/gallery/g85.jpg'},
     {image : 'assets/gallery/g86.jpg'},
     {image : 'assets/gallery/g87.jpg'},
     {image : 'assets/gallery/g88.jpg'},
     {image : 'assets/gallery/g89.jpg'},
     {image : 'assets/gallery/g90.jpg'},
     {image : 'assets/gallery/g91.jpg'},
     {image : 'assets/gallery/g92.jpg'},
     {image : 'assets/gallery/g93.jpg'},
     {image : 'assets/gallery/g94.jpg'},
     {image : 'assets/gallery/g95.jpg'},
     {image : 'assets/gallery/g96.jpg'},
     {image : 'assets/gallery/g97.jpg'},
     {image : 'assets/gallery/g98.jpg'},
     {image : 'assets/gallery/g99.jpg'},
     {image : 'assets/gallery/g100.jpg'},
     {image : 'assets/gallery/g101.jpg'},
     {image : 'assets/gallery/g102.jpg'},
    //  {image : 'assets/gallery/g103.jpg'},
     {image : 'assets/gallery/g104.jpg'},
     {image : 'assets/gallery/g105.jpg'},
    //  {image : 'assets/gallery/g106.jpg'},
     {image : 'assets/gallery/g107.jpg'},
     {image : 'assets/gallery/g108.jpg'},
     {image : 'assets/gallery/g109.jpg'},
     {image : 'assets/gallery/g110.jpg'},
     {image : 'assets/gallery/g111.jpg'},
     {image : 'assets/gallery/g112.jpg'},
     {image : 'assets/gallery/g113.jpg'},
     {image : 'assets/gallery/g114.jpg'},
 
    //  27/09/2021
     {image : 'assets/gallery/folder_1/114.jpg'},
     {image : 'assets/gallery/folder_1/115.jpg'},
     {image : 'assets/gallery/folder_1/116.jpg'},
     {image : 'assets/gallery/folder_1/115a.jpg'},
     {image : 'assets/gallery/folder_1/117.jpg'},
     {image : 'assets/gallery/folder_1/118.jpg'},
     {image : 'assets/gallery/folder_1/119.jpg'},
    //  {image : 'assets/gallery/folder_1/120.jpg'},
     {image : 'assets/gallery/folder_1/121.jpg'},
    //  {image : 'assets/gallery/folder_1/122.jpg'},
     {image : 'assets/gallery/folder_1/123.jpg'},
     {image : 'assets/gallery/folder_1/124.jpg'},
     {image : 'assets/gallery/folder_1/125.jpg'},
    //  {image : 'assets/gallery/folder_1/126.jpg'},
    //  {image : 'assets/gallery/folder_1/127.jpg'},
     {image : 'assets/gallery/folder_1/128.jpg'},
    //  {image : 'assets/gallery/folder_1/129.jpg'},
     {image : 'assets/gallery/folder_1/130.jpg'},
    //  {image : 'assets/gallery/folder_1/131.jpg'},
     {image : 'assets/gallery/folder_1/132.jpg'},
     {image : 'assets/gallery/folder_1/133.jpg'},
     {image : 'assets/gallery/folder_1/134.jpg'},
     {image : 'assets/gallery/folder_1/135.jpg'},
     {image : 'assets/gallery/folder_1/136.jpg'},
     {image : 'assets/gallery/folder_1/137.jpg'},
     {image : 'assets/gallery/folder_1/138.jpg'},
     {image : 'assets/gallery/folder_1/139.jpg'},
     {image : 'assets/gallery/folder_1/140.jpg'},
     {image : 'assets/gallery/folder_1/141.jpg'},
     {image : 'assets/gallery/folder_1/142.jpg'},
    //  {image : 'assets/gallery/folder_1/143.jpg'},
     {image : 'assets/gallery/folder_1/145.jpg'},
     {image : 'assets/gallery/folder_1/146.jpg'},
    //  {image : 'assets/gallery/folder_1/147.jpg'},
     {image : 'assets/gallery/folder_1/148.jpg'},
     {image : 'assets/gallery/folder_1/149.jpg'},
     {image : 'assets/gallery/folder_1/150.jpg'},
     {image : 'assets/gallery/folder_1/151.jpg'},
    //  {image : 'assets/gallery/folder_1/152.jpg'},
     {image : 'assets/gallery/folder_1/153.jpg'},
     {image : 'assets/gallery/folder_1/154.jpg'},
     {image : 'assets/gallery/folder_1/156.jpg'},
     {image : 'assets/gallery/folder_1/157.jpg'},
    //  {image : 'assets/gallery/folder_1/158.jpg'},
     {image : 'assets/gallery/folder_1/159.jpg'},
     {image : 'assets/gallery/folder_1/160.jpg'},
     {image : 'assets/gallery/folder_1/161.jpg'},
     {image : 'assets/gallery/folder_1/162.jpg'},
     {image : 'assets/gallery/folder_1/163.jpg'},
     {image : 'assets/gallery/folder_1/164.jpg'},
     {image : 'assets/gallery/folder_1/165.jpg'},
     {image : 'assets/gallery/folder_1/167.jpg'},
     {image : 'assets/gallery/folder_1/168.jpg'},
     {image : 'assets/gallery/folder_1/169.jpg'},
     {image : 'assets/gallery/folder_1/170.jpg'},
     {image : 'assets/gallery/folder_1/171.jpg'},
     {image : 'assets/gallery/folder_1/172.jpg'},
     {image : 'assets/gallery/folder_1/173.jpg'},
     {image : 'assets/gallery/folder_1/174.jpg'},
     {image : 'assets/gallery/folder_1/175.jpg'},
     {image : 'assets/gallery/folder_1/178.jpg'},
    //  {image : 'assets/gallery/folder_1/179.jpg'},
     {image : 'assets/gallery/folder_1/180.jpg'},
    //  {image : 'assets/gallery/folder_1/181.jpg'},
     {image : 'assets/gallery/folder_1/182.jpg'},
     {image : 'assets/gallery/folder_1/183.jpg'},
     {image : 'assets/gallery/folder_1/184.jpg'},
    //  {image : 'assets/gallery/folder_1/185.jpg'},
     {image : 'assets/gallery/folder_1/186.jpg'},
     {image : 'assets/gallery/folder_1/187.jpg'},
     {image : 'assets/gallery/folder_1/188.jpg'},
    //  {image : 'assets/gallery/folder_1/189.jpg'},
     {image : 'assets/gallery/folder_1/190.jpg'},
     {image : 'assets/gallery/folder_1/191.jpg'},
     {image : 'assets/gallery/folder_1/192.jpg'},
    //  {image : 'assets/gallery/folder_1/193.jpg'},
     {image : 'assets/gallery/folder_1/194.jpg'},
     {image : 'assets/gallery/folder_1/195.jpg'},
     {image : 'assets/gallery/folder_1/196.jpg'},
     {image : 'assets/gallery/folder_1/197.jpg'},
     {image : 'assets/gallery/folder_1/198.jpg'},
     {image : 'assets/gallery/folder_1/199.jpg'},
     {image : 'assets/gallery/folder_1/200.jpg'},
     {image : 'assets/gallery/folder_1/201.jpg'},
     {image : 'assets/gallery/folder_1/202.jpg'},
     {image : 'assets/gallery/folder_1/203.jpg'},
     {image : 'assets/gallery/folder_1/204.jpg'},
     {image : 'assets/gallery/folder_1/205.jpg'},
     {image : 'assets/gallery/folder_1/206.jpg'},
     {image : 'assets/gallery/folder_1/207.jpg'},
     {image : 'assets/gallery/folder_1/208.jpg'},
     {image : 'assets/gallery/folder_1/209.jpg'},
     {image : 'assets/gallery/folder_1/210.jpg'},
     {image : 'assets/gallery/folder_1/211.jpg'},
     {image : 'assets/gallery/folder_1/212.jpg'},
     {image : 'assets/gallery/folder_1/213.jpg'},
     {image : 'assets/gallery/folder_1/214.jpg'},
     {image : 'assets/gallery/folder_1/215.jpg'},
     {image : 'assets/gallery/folder_1/216.jpg'},
     {image : 'assets/gallery/folder_1/217.jpg'},
     {image : 'assets/gallery/folder_1/218.jpg'},
     {image : 'assets/gallery/folder_1/219.jpg'},
     {image : 'assets/gallery/folder_1/220.jpg'},
     {image : 'assets/gallery/folder_1/221.jpg'},
    //  {image : 'assets/gallery/folder_1/222.jpg'},
    //  {image : 'assets/gallery/folder_1/223.jpg'},
    //  {image : 'assets/gallery/folder_1/224.jpg'},
    //  {image : 'assets/gallery/folder_1/225.jpg'},
    //  {image : 'assets/gallery/folder_1/226.jpg'},
    //  {image : 'assets/gallery/folder_1/227.jpg'},
    //  {image : 'assets/gallery/folder_1/228.jpg'},
     {image : 'assets/gallery/folder_1/229.jpg'},
     {image : 'assets/gallery/folder_1/230.jpg'},
     {image : 'assets/gallery/folder_1/231.jpg'},
     {image : 'assets/gallery/folder_1/232.jpg'},
     {image : 'assets/gallery/folder_1/234.jpg'},
     {image : 'assets/gallery/folder_1/235.jpg'},
     {image : 'assets/gallery/folder_1/236.jpg'},
     {image : 'assets/gallery/folder_1/237.jpg'},
     {image : 'assets/gallery/folder_1/238.jpg'},
     {image : 'assets/gallery/folder_1/239.jpg'},
     {image : 'assets/gallery/folder_1/240.jpg'},
     {image : 'assets/gallery/folder_1/241.jpg'},
     {image : 'assets/gallery/folder_1/242.jpg'},
     {image : 'assets/gallery/folder_1/243.jpg'},
     {image : 'assets/gallery/folder_1/244.jpg'},
     {image : 'assets/gallery/folder_1/245.jpg'},
     {image : 'assets/gallery/folder_1/246.jpg'},
     {image : 'assets/gallery/folder_1/247.jpg'},
     {image : 'assets/gallery/folder_1/248.jpg'},
     {image : 'assets/gallery/folder_1/249.jpg'},
     {image : 'assets/gallery/folder_1/250.jpg'},
     {image : 'assets/gallery/folder_1/251.jpg'},
     {image : 'assets/gallery/folder_1/252.jpg'},
     {image : 'assets/gallery/folder_1/253.jpg'},
     {image : 'assets/gallery/folder_1/254.jpg'},
     {image : 'assets/gallery/folder_1/256.jpg'},
     {image : 'assets/gallery/folder_1/257.jpg'},
     {image : 'assets/gallery/folder_1/258.jpg'},
     {image : 'assets/gallery/folder_1/259.jpg'},
     {image : 'assets/gallery/folder_1/260.jpg'},
     // height images
     {image : 'assets/gallery/folder_1/1.jpg'},
     {image : 'assets/gallery/folder_1/2.jpg'},
     {image : 'assets/gallery/folder_1/3.jpg'},
     {image : 'assets/gallery/folder_1/4.jpg'},
     {image : 'assets/gallery/folder_1/5.jpg'},
     {image : 'assets/gallery/folder_1/6.jpg'},
    //  {image : 'assets/gallery/folder_1/7.jpg'},
     {image : 'assets/gallery/folder_1/8.jpg'},
     {image : 'assets/gallery/folder_1/9.jpg'},
    //  {image : 'assets/gallery/folder_1/10.jpg'},
     {image : 'assets/gallery/folder_1/11.jpg'},
     {image : 'assets/gallery/folder_1/12.jpg'},
     {image : 'assets/gallery/folder_1/13.jpg'},
     {image : 'assets/gallery/folder_1/14.jpg'},
     {image : 'assets/gallery/folder_1/15.jpg'},
     {image : 'assets/gallery/folder_1/16.jpg'},
     {image : 'assets/gallery/folder_1/17.jpg'},
     {image : 'assets/gallery/folder_1/18.jpg'},
     {image : 'assets/gallery/folder_1/19.jpg'},
     {image : 'assets/gallery/folder_1/20.jpg'},
     {image : 'assets/gallery/folder_1/21.jpg'},
     {image : 'assets/gallery/folder_1/22.jpg'},
     {image : 'assets/gallery/folder_1/23.jpg'},
     {image : 'assets/gallery/folder_1/24.jpg'},
     {image : 'assets/gallery/folder_1/25.jpg'},
     {image : 'assets/gallery/folder_1/26.jpg'},
     {image : 'assets/gallery/folder_1/27.jpg'},
     {image : 'assets/gallery/folder_1/28.jpg'},
     {image : 'assets/gallery/folder_1/29.jpg'},
     {image : 'assets/gallery/folder_1/30.jpg'},
    //  {image : 'assets/gallery/folder_1/31.jpg'},
     {image : 'assets/gallery/folder_1/32.jpg'},
     {image : 'assets/gallery/folder_1/33.jpg'},
     {image : 'assets/gallery/folder_1/34.jpg'},
     {image : 'assets/gallery/folder_1/35.jpg'},
     {image : 'assets/gallery/folder_1/36.jpg'},
     {image : 'assets/gallery/folder_1/37.jpg'},
     {image : 'assets/gallery/folder_1/38.jpg'},
     {image : 'assets/gallery/folder_1/39.jpg'},
     {image : 'assets/gallery/folder_1/40.jpg'},
    //  {image : 'assets/gallery/folder_1/41.jpg'},
     {image : 'assets/gallery/folder_1/42.jpg'},
     {image : 'assets/gallery/folder_1/43.jpg'},
     {image : 'assets/gallery/folder_1/44.jpg'},
     {image : 'assets/gallery/folder_1/45.jpg'},
     {image : 'assets/gallery/folder_1/46.jpg'},
     {image : 'assets/gallery/folder_1/47.jpg'},
     {image : 'assets/gallery/folder_1/48.jpg'},
     {image : 'assets/gallery/folder_1/49.jpg'},
     {image : 'assets/gallery/folder_1/50.jpg'},
     {image : 'assets/gallery/folder_1/51.jpg'},
     {image : 'assets/gallery/folder_1/52.jpg'},
     {image : 'assets/gallery/folder_1/53.jpg'},
     {image : 'assets/gallery/folder_1/54.jpg'},
     {image : 'assets/gallery/folder_1/55.jpg'},
     {image : 'assets/gallery/folder_1/56.jpg'},
     {image : 'assets/gallery/folder_1/57.jpg'},
     {image : 'assets/gallery/folder_1/58.jpg'},
     {image : 'assets/gallery/folder_1/59.jpg'},
     {image : 'assets/gallery/folder_1/60.jpg'},
     {image : 'assets/gallery/folder_1/61.jpg'},
     {image : 'assets/gallery/folder_1/62.jpg'},
     {image : 'assets/gallery/folder_1/64.jpg'},
     {image : 'assets/gallery/folder_1/65.jpg'},
     {image : 'assets/gallery/folder_1/66.jpg'},
     {image : 'assets/gallery/folder_1/67.jpg'},
     {image : 'assets/gallery/folder_1/68.jpg'},
     {image : 'assets/gallery/folder_1/69.jpg'},
     {image : 'assets/gallery/folder_1/70.jpg'},
     {image : 'assets/gallery/folder_1/71.jpg'},
     {image : 'assets/gallery/folder_1/72.jpg'},
     {image : 'assets/gallery/folder_1/73.jpg'},
     {image : 'assets/gallery/folder_1/74.jpg'},
     {image : 'assets/gallery/folder_1/75.jpg'},
     {image : 'assets/gallery/folder_1/76.jpg'},
     {image : 'assets/gallery/folder_1/77.jpg'},
     {image : 'assets/gallery/folder_1/78.jpg'},
     {image : 'assets/gallery/folder_1/79.jpg'},
     {image : 'assets/gallery/folder_1/80.jpg'},
     {image : 'assets/gallery/folder_1/81.jpg'},
     {image : 'assets/gallery/folder_1/82.jpg'},
     {image : 'assets/gallery/folder_1/83.jpg'},
     {image : 'assets/gallery/folder_1/84.jpg'},
     {image : 'assets/gallery/folder_1/85.jpg'},
     {image : 'assets/gallery/folder_1/86.jpg'},
     {image : 'assets/gallery/folder_1/87.jpg'},
     {image : 'assets/gallery/folder_1/88.jpg'},
     {image : 'assets/gallery/folder_1/89.jpg'},
     {image : 'assets/gallery/folder_1/90.jpg'},
     {image : 'assets/gallery/folder_1/91.jpg'},
     {image : 'assets/gallery/folder_1/92.jpg'},
     {image : 'assets/gallery/folder_1/93.jpg'},
     {image : 'assets/gallery/folder_1/94.jpg'},
     {image : 'assets/gallery/folder_1/95.jpg'},
     {image : 'assets/gallery/folder_1/96.jpg'},
     {image : 'assets/gallery/folder_1/97.jpg'},
     {image : 'assets/gallery/folder_1/98.jpg'},
     {image : 'assets/gallery/folder_1/99.jpg'},
     {image : 'assets/gallery/folder_1/100.jpg'},
     {image : 'assets/gallery/folder_1/101.jpg'},
     {image : 'assets/gallery/folder_1/102.jpg'},
     {image : 'assets/gallery/folder_1/103.jpg'},
     {image : 'assets/gallery/folder_1/104.jpg'},
     {image : 'assets/gallery/folder_1/105.jpg'},
     {image : 'assets/gallery/folder_1/106.jpg'},
     {image : 'assets/gallery/folder_1/107.jpg'},
     {image : 'assets/gallery/folder_1/108.jpg'},
     {image : 'assets/gallery/folder_1/109.jpg'},
     {image : 'assets/gallery/folder_1/110.jpg'},
     {image : 'assets/gallery/folder_1/111.jpg'},
     {image : 'assets/gallery/folder_1/112.jpg'},
     {image : 'assets/gallery/folder_1/113.jpg'},
     {image : 'assets/gallery/folder_1/113a.jpg'},
     {image : 'assets/gallery/folder_1/113b.jpg'},
     {image : 'assets/gallery/folder_1/113c.jpg'}
]

const displayImages = document.querySelector('.gallery-items');
(function(){
    let displayItems = galleryItems.map((item, index) => {
         const {image} = item;
         return `
             <div class="col-lg-3 col-md-4 col-6 thumb" id=${index}>
             <a class=thumbnail href=# data-image-id data-toggle=modal data-title data-image=${image} data-target=#image-gallery>
             <img class=img-thumbnail src=${image} alt="Praveen Kumar singer">
             </a>
             </div>`
     })
     displayItems = displayItems.join('');
     displayImages.innerHTML = displayItems;
})();

